services:
  ollama:
    image: "ollama/ollama:latest"
    restart: always
    pull_policy: always
    ports:
      - "11434:11434"
    volumes:
      - website_ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    pull_policy: always
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - website_open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      WEBUI_NAME: "Chaat GPT"

volumes:
  website_ollama:
    external: true
  website_open-webui:
    external: true
